steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "europe-west1-docker.pkg.dev/$PROJECT_ID/qa-metrics/qa-ingestors:latest"
      - "-t"
      - "europe-west1-docker.pkg.dev/$PROJECT_ID/qa-metrics/qa-ingestors:$SHORT_SHA"
      - "."

images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/qa-metrics/qa-ingestors:latest"
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/qa-metrics/qa-ingestors:$SHORT_SHA"
