substitutions:
  _REGION: europe-west1
  _REPOSITORY: qa-metrics
  _BQ_PROJECT: $PROJECT_ID
  _BQ_DATASET: qa_metrics
  _BQ_LOCATION: europe-west1
  _BUGSNAG_SERVICE: bugsnag-ingest-function
  _JIRA_SERVICE: jira-ingest-function
  _TESTRAIL_SERVICE: testrail-ingest-function
  _GAMEBENCH_SERVICE: gamebench-ingest-function
  _BQ_PROJECT: qa-panda-metrics-dev
  _BQ_DATASET: qa_metrics_simple
  _BQ_LOCATION: EU

steps:
  # Build one immutable image per service from the shared simple/Dockerfile
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "simple/Dockerfile"
      - "--build-arg"
      - "SIMPLE_FUNCTION=${_BUGSNAG_SERVICE}"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_BUGSNAG_SERVICE}:$SHORT_SHA"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "simple/Dockerfile"
      - "--build-arg"
      - "SIMPLE_FUNCTION=${_JIRA_SERVICE}"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_JIRA_SERVICE}:$SHORT_SHA"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "simple/Dockerfile"
      - "--build-arg"
      - "SIMPLE_FUNCTION=${_TESTRAIL_SERVICE}"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_TESTRAIL_SERVICE}:$SHORT_SHA"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "simple/Dockerfile"
      - "--build-arg"
      - "SIMPLE_FUNCTION=${_GAMEBENCH_SERVICE}"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_GAMEBENCH_SERVICE}:$SHORT_SHA"
      - "."

  # Deploy each service with its own immutable image
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_BUGSNAG_SERVICE}"
      - "--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_BUGSNAG_SERVICE}:$SHORT_SHA"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--no-allow-unauthenticated"
      - "--update-env-vars=BQ_PROJECT=${_BQ_PROJECT},BQ_DATASET=${_BQ_DATASET},BQ_LOCATION=${_BQ_LOCATION}"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_JIRA_SERVICE}"
      - "--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_JIRA_SERVICE}:$SHORT_SHA"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--update-env-vars=BQ_PROJECT=$PROJECT_ID,BQ_DATASET=qa_metrics_simple,BQ_LOCATION=EU"
      - "--no-allow-unauthenticated"
      - "--update-env-vars=BQ_PROJECT=${_BQ_PROJECT},BQ_DATASET=${_BQ_DATASET},BQ_LOCATION=${_BQ_LOCATION}"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_TESTRAIL_SERVICE}"
      - "--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_TESTRAIL_SERVICE}:$SHORT_SHA"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--no-allow-unauthenticated"
      - "--update-env-vars=BQ_PROJECT=${_BQ_PROJECT},BQ_DATASET=${_BQ_DATASET},BQ_LOCATION=${_BQ_LOCATION}"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_GAMEBENCH_SERVICE}"
      - "--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_GAMEBENCH_SERVICE}:$SHORT_SHA"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--no-allow-unauthenticated"
      - "--update-env-vars=BQ_PROJECT=${_BQ_PROJECT},BQ_DATASET=${_BQ_DATASET},BQ_LOCATION=${_BQ_LOCATION}"

  # Validate service runtime config and startup logs resolve the expected source file.
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        set -euo pipefail

        services=(
          "${_BUGSNAG_SERVICE}:bugsnag"
          "${_JIRA_SERVICE}:jira"
          "${_TESTRAIL_SERVICE}:testrail"
          "${_GAMEBENCH_SERVICE}:gamebench"
        )

        since="$(date -u -d '20 minutes ago' +%Y-%m-%dT%H:%M:%SZ)"

        for row in "${services[@]}"; do
          service="${row%%:*}"
          source="${row##*:}"

          args_value="$(gcloud run services describe "${service}" --region="${_REGION}" --format='value(spec.template.spec.containers[0].args)')"
          echo "${service} args: ${args_value}"

          logs="$(gcloud logging read "resource.type=cloud_run_revision AND resource.labels.service_name=${service} AND timestamp>=\"${since}\"" --limit=200 --format='value(textPayload)')"

          if [ -n "${args_value}" ]; then
            echo "${args_value}" | grep -F -- "${source}/main.py" >/dev/null || {
              echo "${service}: args do not reference ${source}/main.py" >&2
              exit 1
            }
          else
            echo "${logs}" | grep -F -- "Using source: ${source}/main.py" >/dev/null || {
              echo "${service}: startup log missing 'Using source: ${source}/main.py'" >&2
              exit 1
            }
          fi

          env_pairs="$(gcloud run services describe "${service}" --region="${_REGION}" --format='csv[no-heading](spec.template.spec.containers[0].env[].name,spec.template.spec.containers[0].env[].value)')"

          for expected in \
            "BQ_PROJECT,${_BQ_PROJECT}" \
            "BQ_DATASET,${_BQ_DATASET}" \
            "BQ_LOCATION,${_BQ_LOCATION}"; do
            echo "${env_pairs}" | grep -F -- "${expected}" >/dev/null || {
              echo "${service}: env vars missing or mismatch for ${expected}" >&2
              exit 1
            }
          done

          # Post-deploy anti-mix validation: fail if service logs reference another source.
          case "${source}" in
            bugsnag)
              forbidden='jira/main.py|testrail/main.py|gamebench/main.py|/app/main.py'
              ;;
            jira)
              forbidden='bugsnag/main.py|testrail/main.py|gamebench/main.py|BUGSNAG_BASE_URL|/app/main.py'
              ;;
            testrail)
              forbidden='bugsnag/main.py|jira/main.py|gamebench/main.py|BUGSNAG_BASE_URL|/app/main.py'
              ;;
            gamebench)
              forbidden='bugsnag/main.py|jira/main.py|testrail/main.py|BUGSNAG_BASE_URL|/app/main.py'
              ;;
          esac

          if echo "${logs}" | grep -E -- "${forbidden}"; then
            echo "${service}: found forbidden cross-source reference in logs" >&2
            exit 1
          fi
        done

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_BUGSNAG_SERVICE}:$SHORT_SHA"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_JIRA_SERVICE}:$SHORT_SHA"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_TESTRAIL_SERVICE}:$SHORT_SHA"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_GAMEBENCH_SERVICE}:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
