substitutions:
  _REGION: europe-west1
  _REPOSITORY: qa-metrics
  _BUGSNAG_SERVICE: bugsnag-ingest-function
  _JIRA_SERVICE: jira-ingest-function
  _TESTRAIL_SERVICE: testrail-ingest-function
  _GAMEBENCH_SERVICE: gamebench-ingest-function

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "simple/Dockerfile"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_BUGSNAG_SERVICE}:$SHORT_SHA"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_JIRA_SERVICE}:$SHORT_SHA"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_TESTRAIL_SERVICE}:$SHORT_SHA"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_GAMEBENCH_SERVICE}:$SHORT_SHA"
      - "."

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_BUGSNAG_SERVICE}"
      - "--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_BUGSNAG_SERVICE}:$SHORT_SHA"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--no-allow-unauthenticated"
      - "--command=sh"
      - "--args=-c,functions-framework --target=hello_http --source=bugsnag/main.py --port=${PORT}"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_JIRA_SERVICE}"
      - "--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_JIRA_SERVICE}:$SHORT_SHA"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--no-allow-unauthenticated"
      - "--command=sh"
      - "--args=-c,functions-framework --target=hello_http --source=jira/main.py --port=${PORT}"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_TESTRAIL_SERVICE}"
      - "--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_TESTRAIL_SERVICE}:$SHORT_SHA"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--no-allow-unauthenticated"
      - "--command=sh"
      - "--args=-c,functions-framework --target=hello_http --source=testrail/main.py --port=${PORT}"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_GAMEBENCH_SERVICE}"
      - "--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_GAMEBENCH_SERVICE}:$SHORT_SHA"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--no-allow-unauthenticated"
      - "--command=sh"
      - "--args=-c,functions-framework --target=hello_http --source=gamebench/main.py --port=${PORT}"

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_BUGSNAG_SERVICE}:$SHORT_SHA"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_JIRA_SERVICE}:$SHORT_SHA"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_TESTRAIL_SERVICE}:$SHORT_SHA"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_GAMEBENCH_SERVICE}:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
